CREATE TABLE author
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name  VARCHAR(255)
);

CREATE TABLE book
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255),
    author_id INTEGER NOT NULL REFERENCES author(id) ON DELETE CASCADE
);

INSERT INTO author(first_name, last_name) VALUES('John', 'Doe'), ('Jane', 'Doe');
INSERT INTO book(title, author_id) VALUES('John First Book', 1), ('Jane First Book', 2);
